export const COLOURS = {
  white: '#ffffff',
  black: '#000000',
  lightGray: '#B3B4B6',
  accent: '#FFC231',
  accentRed: '#FB5D2E',
  accentPink: '#F96165',
};

export const Categories = [
  {
    name: 'Burger',
    image: require('./images/burger.png'),
    items: [
      {
        name: 'Classic Burger',
        weight: 120,
        rating: '5.0',
        price: 199,
        isTopOfTheWeek: true,
        image: require('./images/burger/classicburger.png'),
        size: 'Large 8"',
        crust: 'Thick Crust',
        delivery: 25,
        ingredients: [
          require('./images/flour.png'),
          require('./images/cheese.png'),
          require('./images/Sliced-Onion.png'),
          require('./images/Tomato.png'),
        ],
      },
      {
        name: 'Aloo Tikki Burger',
        weight: 150,
        rating: '4.5',
        price: 99,
        isTopOfTheWeek: false,
        image: require('./images/burger/alootikkiburger.png'),
        size: 'Large 12"',
        crust: 'Thick Crust',
        delivery: 20,
        ingredients: [
          require('./images/Sliced-Onion.png'),
          require('./images/Tomato.png'),
          require('./images/cheese.png'),
          require('./images/flour.png'),
        ],
      },
      {
        name: 'Biggie Cheese',
        weight: 250,
        rating: '4.2',
        price: 299,
        isTopOfTheWeek: false,
        image: require('./images/burger/biggiecheese.png'),
        size: 'Large 10"',
        crust: 'Thick Crust',
        delivery: 35,
        ingredients: [
          require('./images/Tomato.png'),
          require('./images/cheese.png'),
          require('./images/Sliced-Onion.png'),
          require('./images/flour.png'),
        ],
      },
    ],
  },
  {
    name: 'Pizza',
    image: require('./images/pizza.png'),
    items: [
      {
        name: 'Pepperoni Pizza',
        weight: 250,
        rating: '5.0',
        price: 199,
        isTopOfTheWeek: true,
        image: require('./images/pizza/pepperonipizza.png'),
        size: 'Large 14"',
        crust: 'Thin Crust',
        delivery: 30,
        ingredients: [
          require('./images/Tomato.png'),
          require('./images/cheese.png'),
          require('./images/Sliced-Onion.png'),
          require('./images/flour.png'),
        ],
      },
      {
        name: 'Plain Cheese Pizza',
        weight: 300,
        rating: '4.5',
        price: 299,
        isTopOfTheWeek: false,
        image: require('./images/pizza/plaincheesepizza.png'),
        size: 'Large 16"',
        crust: 'Thin Cheese',
        delivery: 25,
        ingredients: [
          require('./images/Sliced-Onion.png'),
          require('./images/flour.png'),
          require('./images/cheese.png'),
          require('./images/Tomato.png'),
        ],
      },
      {
        name: 'Mexican Green Wave',
        weight: 350,
        rating: '4.2',
        price: 499,
        isTopOfTheWeek: false,
        image: require('./images/pizza/mexicangreenwave.png'),
        size: 'Large 15"',
        crust: 'Thin Crust',
        delivery: 45,
        ingredients: [
          require('./images/flour.png'),
          require('./images/cheese.png'),
          require('./images/Tomato.png'),
          require('./images/Sliced-Onion.png'),
        ],
      },
    ],
  },
  {
    name: 'Soft Drinks',
    image: require('./images/softdrinks.png'),
    items: [
      {
        name: 'Coco Cola',
        weight: 200,
        rating: '5.0',
        price: 299,
        isTopOfTheWeek: true,
        image: require('./images/softdrinks/cocacola.png'),
        size: 'Medium Glass',
        crust: 'Small Ice',
        delivery: 10,
        ingredients: [require('./images/softdrinks/cocacola.png')],
      },
      {
        name: 'Orange Juice',
        weight: 500,
        rating: '4.5',
        price: 199,
        isTopOfTheWeek: false,
        image: require('./images/softdrinks/orange.png'),
        size: 'LArge Glass',
        crust: 'Large Ice',
        delivery: 8,
        ingredients: [require('./images/softdrinks/orange.png')],
      },
      {
        name: 'Mango Juice',
        weight: 150,
        rating: '4.2',
        price: 99,
        isTopOfTheWeek: false,
        image: require('./images/softdrinks/mango.png'),
        size: 'Large Glass',
        crust: 'Small Ice',
        delivery: 5,
        ingredients: [require('./images/softdrinks/mango.png')],
      },
    ],
  },
];
